<a href="https://colab.research.google.com/github/Dryele/I.A/blob/main/IA_Exerc%C3%ADcio_06_Rede_Neural_Artificial_Python_SkLearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Treinamento

### Carregando Arquivo de Treinamento (.csv)

In [ ]:
import pandas as pd
# Carregando dados do arquivo CSV
url = 'https://raw.githubusercontent.com/alcidesbenicasa/IA---2020.1---Exerc-cio---06---Rede-Neural-Artificial/main/dados_pacientes_treinamento.csv'
base_Treinamento = pd.read_csv(url,sep=';', encoding = 'latin1').values
print("---------------------------------")
print("Dados dos Pacientes - TREINAMENTO")
print("---------------------------------")
print(base_Treinamento)
print("---------------------------------")

# Extração dos Atributos a serem utilizadas pela rede
print("Atributos de Entrada")
print("---------------------------------")
print(base_Treinamento[:, 1:5])

print("----------------------------")
print("Classificação Supervisionada")
print("----------------------------")
print(base_Treinamento[:, 5])

---------------------------------
Dados dos Pacientes - TREINAMENTO
---------------------------------
[['João' 'sim' 'sim' 'pequenas' 'sim' 'doente']
 ['Pedro' 'não' 'não' 'grandes' 'não' 'saudável']
 ['Maria' 'sim' 'sim' 'pequenas' 'não' 'saudável']
 ['José' 'sim' 'não' 'grandes' 'sim' 'doente']
 ['Ana' 'sim' 'não' 'pequenas' 'sim' 'saudável']
 ['Leila' 'não' 'não' 'grandes' 'sim' 'doente']]
---------------------------------
Atributos de Entrada
---------------------------------
[['sim' 'sim' 'pequenas' 'sim']
 ['não' 'não' 'grandes' 'não']
 ['sim' 'sim' 'pequenas' 'não']
 ['sim' 'não' 'grandes' 'sim']
 ['sim' 'não' 'pequenas' 'sim']
 ['não' 'não' 'grandes' 'sim']]
----------------------------
Classificação Supervisionada
----------------------------
['doente' 'saudável' 'saudável' 'doente' 'saudável' 'doente']


### Pré-processamento de Dados

In [1]:
import numpy as np 
from sklearn import preprocessing

# Binarizador de rótulo
lb = preprocessing.LabelBinarizer()

#A saída da transformação é também conhecido como codificação 1-de-n
#Transforma valores categóricos equidistantes em valores binários equidistantes.
#Atributos categóricos com valores sim e não
lb.fit(['sim', 'não'])
febre = lb.transform(base_Treinamento[:,1])  
enjoo = lb.transform(base_Treinamento[:,2])
dores = lb.transform(base_Treinamento[:,4])

#Atributos categóricos com valores pequenas e grandes
lb.fit(['grandes', 'pequenas'])
manchas = lb.transform(base_Treinamento[:,3])

#Atributos categóricos com valores saudável e doente
lb.fit(['saudável', 'doente'])
classes = lb.transform(base_Treinamento[:,5])

#Concatenação de Atributos (Colunas) 
atributos_norm = np.column_stack((febre,enjoo,manchas,dores))
print("--------------------------------")
print("Atributos de Entrada - Numéricos")
print("--------------------------------")
print(atributos_norm)

print("----------------------------------------")
print("Classificação Supervisionada - Numéricos")
print("----------------------------------------")
diagnostico_norm = np.hstack((classes))
print(diagnostico_norm)

NameError: ignored

### Treinamento do Neurônio Perceptron

In [ ]:
from sklearn.linear_model import Perceptron
# Treinamento do Perceptron a partir dos atributos de entrada e classificações
modelo = Perceptron()
modelo.fit(atributos_norm, diagnostico_norm)

# Acurácia do modelo, que é : 1 - (predições erradas / total de predições)
# Acurácia do modelo: indica uma performance geral do modelo. 
# Dentre todas as classificações, quantas o modelo classificou corretamente;
# (VP+VN)/N
print('Acurácia: %.3f' % modelo.score(atributos_norm, diagnostico_norm))

Acurácia: 1.000


### ----------------------------------------------------------------------------

# Validação do Aprendizado 

### Predição Simples

In [ ]:
Luiz = [[0,0,1,1]]
print("Luiz", modelo.predict(Luiz))
Laura = [[1,1,0,1]]
print("Laura", modelo.predict(Laura))

Luiz [0]
Laura [0]


### Predição a partir de base de dados (.csv)

In [ ]:
import pandas as pd
# Carregando dados do arquivo CSV
url = 'https://raw.githubusercontent.com/alcidesbenicasa/IA---2020.1---Exerc-cio---06---Rede-Neural-Artificial/main/dados_pacientes_teste.csv'
base_Testes = pd.read_csv(url,sep=';', encoding = 'latin1').values
print("----------------------------")
print("Dados dos Pacientes - TESTES")
print("----------------------------")
print(base_Testes)
print("---------------------------------")

# Extração dos Atributos a serem utilizadas pela rede
print("Atributos de Entrada")
print("---------------------------------")
print(base_Testes[:, 1:5])

----------------------------
Dados dos Pacientes - TESTES
----------------------------
[['João' 'sim' 'sim' 'pequenas' 'sim']
 ['Pedro' 'não' 'não' 'grandes' 'não']
 ['Maria' 'sim' 'sim' 'pequenas' 'não']
 ['José' 'sim' 'não' 'grandes' 'sim']
 ['Ana' 'sim' 'não' 'pequenas' 'sim']
 ['Leila' 'não' 'não' 'grandes' 'sim']
 ['Luis' 'não' 'não' 'pequenas' 'sim']
 ['Laura' 'sim' 'sim' 'grandes' 'sim']]
---------------------------------
Atributos de Entrada
---------------------------------
[['sim' 'sim' 'pequenas' 'sim']
 ['não' 'não' 'grandes' 'não']
 ['sim' 'sim' 'pequenas' 'não']
 ['sim' 'não' 'grandes' 'sim']
 ['sim' 'não' 'pequenas' 'sim']
 ['não' 'não' 'grandes' 'sim']
 ['não' 'não' 'pequenas' 'sim']
 ['sim' 'sim' 'grandes' 'sim']]


### Pré-processamento de Dados

In [ ]:
import numpy as np 
from sklearn import preprocessing

# Binarizador de rótulo
lb = preprocessing.LabelBinarizer()

#A saída da transformação é também conhecido como codificação 1-de-n
#Transforma valores categóricos equidistantes em valores binários equidistantes.
#Atributos categóricos com valores sim e não
lb.fit(['sim', 'não'])
febre = lb.transform(base_Testes[:,1])  
enjoo = lb.transform(base_Testes[:,2])
dores = lb.transform(base_Testes[:,4])

#Atributos categóricos com valores pequenas e grandes
lb.fit(['grandes', 'pequenas'])
manchas = lb.transform(base_Testes[:,3])

#Concatenação de Atributos (Colunas) 
atributos_norm = np.column_stack((febre,enjoo,manchas,dores))
print("--------------------------------")
print("Atributos de Entrada - Numéricos")
print("--------------------------------")
print(atributos_norm)


--------------------------------
Atributos de Entrada - Numéricos
--------------------------------
[[1 1 1 1]
 [0 0 0 0]
 [1 1 1 0]
 [1 0 0 1]
 [1 0 1 1]
 [0 0 0 1]
 [0 0 1 1]
 [1 1 0 1]]


### Predição da Base

In [ ]:
base_Predicao = modelo.predict((atributos_norm))
print("Classificações: ", base_Predicao)

Classificações:  [0 1 1 0 1 0 0 0]


### Retorno aos valores Categóricos

In [3]:
import numpy as np 
from sklearn import preprocessing

# Binarizador de rótulo
lb = preprocessing.LabelBinarizer()

#A saída da transformação é também conhecido como codificação 1-de-n
#Transforma valores categóricos equidistantes em valores binários equidistantes.
#Atributos categóricos com valores sim e não
lb.fit(['sim', 'não'])
febre = lb.inverse_transform(atributos_norm[:,0])  
enjoo = lb.inverse_transform(atributos_norm[:,1])
dores = lb.inverse_transform(atributos_norm[:,3])

#Atributos categóricos com valores pequenas e grandes
lb.fit(['grandes', 'pequenas'])
manchas = lb.inverse_transform(atributos_norm[:,2])

#Atributos categóricos com valores saudável e doente
lb.fit(['saudável', 'doente'])
predicao = lb.inverse_transform(base_Predicao)

#Concatenação de Atributos (Colunas) 
atributos_cat = np.column_stack((base_Testes[:,0],febre,enjoo,manchas,dores,predicao))
print("--------------------------------")
print("Atributos de Entrada - Numéricos")
print("--------------------------------")
print(atributos_cat)


NameError: ignored